In [23]:
import numpy as np
import pandas as pd

напишіть функцію гіпотези лінійної регресії у векторному вигляді

In [5]:
def linear_hypothesis(X, w):
    return np.dot(X, w)

створіть функцію для обчислення функції втрат у векторному вигляд

In [6]:
def mean_squared_error(hypothesis, y):
    m = len(y)
    return (1/(2*m)) * np.sum((hypothesis - y)**2)

реалізуйте один крок градієнтного спуску

In [28]:
def gradient_descent_step(X, y, w, alpha):
    m = len(y)
    hypothesis = linear_hypothesis(X, w)
    gradient = np.dot(X.T, (hypothesis - y)) / m
    w = w - alpha * gradient

    return w

знайдіть найкращі параметри w для датасету прогнозуючу ціну на будинок залежно від площі, кількості ванних кімнат та кількості спалень

In [24]:
df = pd.read_csv('Housing.csv')

features = ['area', 'bathrooms', 'bedrooms']
target = 'price'

X_numeric = df[features].values
X_numeric = (X_numeric - np.mean(X_numeric, axis=0)) / np.std(X_numeric, axis=0)
X = np.hstack((np.ones((X_numeric.shape[0], 1)), X_numeric))

num_iterations = 10000
alpha = 0.0001

y = df[target].values.reshape(-1, 1)

w = np.zeros((X.shape[1], 1))

for i in range(num_iterations):
    hypothesis = np.dot(X, w)
    gradient = np.dot(X.T, (hypothesis - y)) / len(y)
    w = w - alpha * gradient

print(w)

[[3013235.23858269]
 [ 568031.81529904]
 [ 510449.14553165]
 [ 312194.01060182]]


знайдіть ці ж параметри за допомогою аналітичного рішення

In [26]:
import pandas as pd
import numpy as np

df = pd.read_csv('Housing.csv')
features = ['area', 'bathrooms', 'bedrooms']
target = 'price'
X_numeric = df[features].values
X = np.hstack((np.ones((X_numeric.shape[0], 1)), X_numeric))
y = df[target].values.reshape(-1, 1)
w = np.linalg.inv(X.T @ X) @ X.T @ y

print(w)

[[-1.73171608e+05]
 [ 3.78762754e+02]
 [ 1.38604950e+06]
 [ 4.06820034e+05]]


порівняйте отримані результати

In [31]:
def find_optimal_parameters(X, y, num_iterations=10000, alpha=0.0001):
    X_normalized = (X[:, 1:] - np.mean(X[:, 1:], axis=0)) / np.std(X[:, 1:], axis=0)
    X_normalized = np.hstack((np.ones((X.shape[0], 1)), X_normalized))

    w = np.zeros((X_normalized.shape[1], 1))

    for _ in range(num_iterations):
        w = gradient_descent_step(X_normalized, y, w, alpha)

    return w

df = pd.read_csv('Housing.csv')

features = ['area', 'bathrooms', 'bedrooms']
target = 'price'

X_numeric = df[features].values
X = np.hstack((np.ones((X_numeric.shape[0], 1)), X_numeric))
y = df[target].values.reshape(-1, 1)

num_iterations = 100000
alpha = 0.01

w_gradient_descent = find_optimal_parameters(X, y, num_iterations, alpha)
w_analytical_solution = np.linalg.inv(X.T @ X) @ X.T @ y

print("Оптимальні параметри за градієнтним спуском:")
print(w_gradient_descent)
print("\nОптимальні параметри за аналітичним рішенням:")
print(w_analytical_solution)


Оптимальні параметри за градієнтним спуском:
[[4766729.24770638]
 [ 821214.14349519]
 [ 695808.52272536]
 [ 299983.57107964]]

Оптимальні параметри за аналітичним рішенням:
[[-1.73171608e+05]
 [ 3.78762754e+02]
 [ 1.38604950e+06]
 [ 4.06820034e+05]]
